#!/usr/bin/env python3
"""Generate test-only C++/Swift entity and field tables from the sync contract.

This does not replace product codecs or change an active capability/default.
The existing field_groups.py gate still checks the handwritten product maps.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
DIRECTORY = pathlib.Path("fixtures/sync-conformance/generated")


def records(root: pathlib.Path) -> list[dict]:
    source = json.loads((root / "config/sync-format.json").read_text())["records"]
    result = []
    ids, names = set(), set()
    for row in source:
        identity, name, version, fields = (
            row["id"], row["dataClass"], row["wireModelVersion"], row["fieldGroups"])
        if (type(identity) is not int or not 0 <= identity <= 2147483647 or identity in ids
                or not isinstance(name, str) or not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", name)
                or name in names or type(version) is not int or not 1 <= version <= 2147483647
                or not isinstance(fields, list) or not fields
                or any(not isinstance(field, str) or not re.fullmatch(r"[a-z][a-z0-9_]*", field)
                       for field in fields) or len(fields) != len(set(fields))):
            raise ValueError("invalid or duplicate sync entity/field catalogue entry")
        ids.add(identity)
        names.add(name)
        result.append({"id": identity, "dataClass": name, "wireModelVersion": version,
                       "fieldGroups": fields})
    if not result:
        raise ValueError("sync entity catalogue is empty")
    return sorted(result, key=lambda row: row["id"])


def render(root: pathlib.Path = ROOT) -> dict[pathlib.Path, str]:
    entities = records(root)
    canonical = json.dumps(entities, sort_keys=True, separators=(",", ":"))
    digest = hashlib.sha256(canonical.encode()).hexdigest()
    banner = ("// Generated by tools/sync_conformance/generate_field_catalogue.py.\n"
              "// Source: config/sync-format.json. Test catalogue only; no runtime activation.\n"
              f"// Contract SHA-256: {digest}\n")
    cpp = [banner, "#ifndef AHOI_SYNC_CONFORMANCE_FIELD_CATALOGUE_H_\n",
           "#define AHOI_SYNC_CONFORMANCE_FIELD_CATALOGUE_H_\n\n",
           "#include <cstddef>\n#include <string_view>\n\n",
           "namespace ahoi::sync::conformance {\n\n",
           "struct EntityFields {\n  int entity_type;\n  std::string_view data_class;\n",
           "  int wire_model_version;\n  const std::string_view* field_groups;\n",
           "  std::size_t field_count;\n};\n\n"]
    for row in entities:
        fields = ", ".join(json.dumps(field) for field in row["fieldGroups"])
        cpp.append(f"inline constexpr std::string_view kEntity{row['id']}Fields[] = {{\n  {fields}\n}};\n")
    cpp.append("\ninline constexpr EntityFields kEntities[] = {\n")
    for row in entities:
        cpp.append(f"  {{{row['id']}, {json.dumps(row['dataClass'])}, {row['wireModelVersion']}, "
                   f"kEntity{row['id']}Fields, {len(row['fieldGroups'])}}},\n")
    cpp.extend(["};\n\n}  // namespace ahoi::sync::conformance\n\n",
                "#endif  // AHOI_SYNC_CONFORMANCE_FIELD_CATALOGUE_H_\n"])
    swift = [banner, "enum SyncConformanceFieldCatalogue {\n",
             "    struct Entry: Sendable {\n        let entityType: Int\n",
             "        let dataClass: String\n        let wireModelVersion: Int\n",
             "        let fieldGroups: [String]\n    }\n\n",
             "    static let entries: [Entry] = [\n"]
    for row in entities:
        fields = ", ".join(json.dumps(field) for field in row["fieldGroups"])
        swift.append(f"        Entry(entityType: {row['id']}, dataClass: {json.dumps(row['dataClass'])},\n"
                     f"              wireModelVersion: {row['wireModelVersion']}, fieldGroups: [{fields}]),\n")
    swift.append("    ]\n}\n")
    manifest = {"schemaVersion": 1, "contractSha256": digest,
                "source": "config/sync-format.json", "records": entities}
    return {
        DIRECTORY / "sync_field_catalogue.h": "".join(cpp),
        DIRECTORY / "SyncFieldCatalogue.swift": "".join(swift),
        DIRECTORY / "field_catalogue.json": json.dumps(manifest, indent=2) + "\n",
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repository", type=pathlib.Path, default=ROOT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    outputs = render(args.repository)
    stale = []
    for relative, data in outputs.items():
        path = args.repository / relative
        if args.check:
            if not path.exists() or path.read_text() != data:
                stale.append(str(relative))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(data)
    if stale:
        print("stale generated sync tables: " + ", ".join(stale), file=sys.stderr)
        return 1
    if not args.check:
        print(f"generated {len(outputs)} C++/Swift/manifest files for {len(records(args.repository))} entity classes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
