# Copyright 2026 The AhoiBrowser Authors
# SPDX-License-Identifier: GPL-3.0-or-later

import("//testing/test.gni")

source_set("popup") {
  sources = [
    "popup_overlay_service.cc",
    "popup_overlay_service.h",
    "popup_types.cc",
    "popup_types.h",
  ]

  public_deps = [
    "//base",
    "//content/public/browser",
    "//third_party/blink/public/mojom:mojom_platform",
    "//ui/base",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "popup_overlay_service_unittest.cc",
    "popup_types_unittest.cc",
  ]
  deps = [
    ":popup",
    "//content/test:test_support",
    "//testing/gtest",
  ]
}

test("ahoi_popup_unittests") {
  deps = [
    ":unit_tests",
    "//content/test:run_all_unittests",
    "//testing/gtest",
  ]
}
