# Copyright 2026 The AhoiBrowser Authors
# SPDX-License-Identifier: GPL-3.0-or-later

import("//testing/test.gni")

source_set("developer_toolkit_ui") {
  sources = [
    "developer_asset_policy_view.cc",
    "developer_asset_policy_view.h",
    "developer_cache_status_view.cc",
    "developer_cache_status_view.h",
    "developer_cookie_manager_view.cc",
    "developer_cookie_manager_view.h",
    "developer_data_clear_view.cc",
    "developer_data_clear_view.h",
    "developer_header_secret_editor_model.cc",
    "developer_header_secret_editor_model.h",
    "developer_header_secret_editor_view.cc",
    "developer_header_secret_editor_view.h",
    "developer_profile_editor_view.cc",
    "developer_profile_editor_view.h",
    "developer_response_header_advanced_mode_view.cc",
    "developer_response_header_advanced_mode_view.h",
    "developer_toolbar_menu_controller.cc",
    "developer_toolbar_menu_controller.h",
    "developer_toolkit_bubble_view.cc",
    "developer_toolkit_bubble_view.h",
    "developer_toolkit_button.cc",
    "developer_toolkit_button.h",
    "developer_toolkit_controller.cc",
    "developer_toolkit_controller.h",
    "location_bar_bubble_button.cc",
    "location_bar_bubble_button.h",
  ]

  public_deps = [
    "//ahoi/browser/developer_toolkit",
    "//base",
  ]

  deps = [
    "//ahoi/browser/developer_toolkit:developer_profile_runtime",
    "//ahoi/browser/ui:visual_style",
    "//ahoi/browser/ui/appearance",
    "//cc/paint",
    "//chrome/app:command_ids",
    "//chrome/app:generated_resources",
    "//chrome/app/vector_icons",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/tabs:tab_strip",
    "//components/embedder_support",
    "//components/embedder_support:user_agent",
    "//components/prefs",
    "//components/vector_icons",
    "//content/public/browser",
    "//crypto",
    "//net",
    "//skia",
    "//ui/accessibility",
    "//ui/base",
    "//ui/color",
    "//ui/gfx",
    "//ui/gfx/animation",
    "//ui/menus",
    "//ui/views",
    "//url",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [
    "developer_asset_policy_view_unittest.cc",
    "developer_cache_status_view_unittest.cc",
    "developer_cookie_manager_view_unittest.cc",
    "developer_data_clear_view_unittest.cc",
    "developer_header_secret_editor_model_unittest.cc",
    "developer_header_secret_editor_view_unittest.cc",
    "developer_response_header_advanced_mode_view_unittest.cc",
    "developer_toolkit_bubble_view_unittest.cc",
    "location_bar_bubble_button_unittest.cc",
  ]
  deps = [
    ":developer_toolkit_ui",
    "//ahoi/browser/ui:visual_style",
    "//base",
    "//testing/gtest",
    "//ui/events:test_support",
    "//ui/views",
    "//ui/views:test_support",
  ]
}

test("ahoi_developer_toolkit_ui_unittests") {
  sources = [ "run_all_unittests.cc" ]
  deps = [
    ":unit_tests",
    "//mojo/core/embedder",
    "//testing/gtest",
    "//ui/base",
    "//ui/resources:ui_test_pak",
    "//ui/views:test_support",
  ]
  data_deps = [ "//ui/resources:ui_test_pak_data" ]
}
