# Copyright 2026 The AhoiBrowser Authors
# SPDX-License-Identifier: GPL-3.0-or-later

import("//testing/test.gni")

source_set("navigation_surface_state") {
  sources = [
    "navigation_surface_state.cc",
    "navigation_surface_state.h",
  ]

  public_deps = [ "//base" ]
}

source_set("navigation_surface_controller") {
  sources = [
    "navigation_surface_controller.cc",
    "navigation_surface_controller.h",
  ]

  public_deps = [
    ":navigation_surface_state",
    "//ahoi/browser/ui/appearance",
    "//base",
    "//components/prefs",
    "//ui/gfx",
    "//ui/gfx/animation",
    "//ui/views",
  ]
  deps = [
    "//ahoi/browser/ui:visual_style",
    "//ui/compositor",
    "//ui/events",
  ]
}

source_set("unit_tests") {
  testonly = true
  sources = [ "navigation_surface_state_unittest.cc" ]
  deps = [
    ":navigation_surface_state",
    "//base/test:test_support",
    "//testing/gtest",
  ]
}

source_set("floating_browser_view_browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
  sources = [ "floating_browser_view_browsertest.cc" ]
  deps = [
    "//ahoi/browser/ui:visual_style",
    "//ahoi/browser/ui/appearance:appearance_preferences",
    "//ahoi/browser/ui/sidebar:browser_sidebar",
    "//base",
    "//chrome/app:generated_resources",
    "//chrome/browser",
    "//chrome/browser/ui",
    "//chrome/browser/ui/views/location_bar",
    "//chrome/browser/ui/views/tabs/vertical",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
    "//components/prefs",
    "//content/test:test_support",
    "//testing/gtest",
    "//ui/accessibility",
    "//ui/base",
    "//ui/compositor",
    "//ui/gfx",
    "//ui/gfx:test_support",
    "//ui/views",
  ]
}

test("ahoi_navigation_surface_state_unittests") {
  sources = [ "run_all_unittests.cc" ]
  deps = [
    ":unit_tests",
    "//base/test:test_support",
    "//testing/gtest",
  ]
}

if (!is_android) {
  test("ahoi_floating_browser_view_browsertests") {
    deps = [
      ":floating_browser_view_browser_tests",
      "//chrome:packed_resources",
      "//chrome/test:browser_tests_runner",
      "//chrome/test:test_support",
    ]
  }
}
